# gradle.properties
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# API base URL for the App
# 模拟器访问宿主机：10.0.2.2
# 真机：电脑局域网 IP + gateway 端口，如 http://192.168.1.100:8088/api/v1/
api.base.url=http://192.168.101.5:8088/api/v1/