package identity

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/epap/api-gateway/config"
)

const redisIntegrationURLEnv = "GATEWAY_REDIS_INTEGRATION_URL"

// redisIntegrationFixture owns only the keys it creates. It deliberately does
// not use SCAN, KEYS, FLUSHDB, or FLUSHALL: an explicitly configured Redis URL
// can point at DB 0 shared with an unrelated local process.
type redisIntegrationFixture struct {
	testingT *testing.T
	url      string
	store    *RedisRecordStore
	prefix   string
	keys     map[string]struct{}
	nextKey  int
}

func newRedisIntegrationFixture(t *testing.T) *redisIntegrationFixture {
	t.Helper()
	url := strings.TrimSpace(os.Getenv(redisIntegrationURLEnv))
	if url == "" {
		t.Skipf("set %s to run against a real Redis server", redisIntegrationURLEnv)
	}

	store, err := NewRedisRecordStore(url)
	if err != nil {
		t.Fatalf("parse %s: %v", redisIntegrationURLEnv, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := store.Ping(ctx); err != nil {
		_ = store.Close()
		t.Fatalf("ping Redis from %s: %v", redisIntegrationURLEnv, err)
	}
	suffix, err := opaqueValue()
	if err != nil {
		_ = store.Close()
		t.Fatalf("create Redis test key prefix: %v", err)
	}
	fixture := &redisIntegrationFixture{
		testingT: t,
		url:      url,
		store:    store,
		prefix:   "axi:test:api-gateway:identity:" + suffix,
		keys:     make(map[string]struct{}),
	}
	t.Cleanup(fixture.cleanup)
	return fixture
}

func (f *redisIntegrationFixture) cleanup() {
	f.testingT.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	for key := range f.keys {
		if err := f.store.Delete(ctx, key); err != nil {
			f.testingT.Errorf("clean up Redis key %q: %v", key, err)
			continue
		}
		if _, err := f.store.Get(ctx, key); !errors.Is(err, ErrRecordNotFound) {
			f.testingT.Errorf("Redis test key %q remained after cleanup: %v", key, err)
		}
	}
	if err := f.store.Close(); err != nil {
		f.testingT.Errorf("close Redis test store: %v", err)
	}
}

func (f *redisIntegrationFixture) key(label string) string {
	f.testingT.Helper()
	f.nextKey++
	key := fmt.Sprintf("%s:%d:%s", f.prefix, f.nextKey, label)
	f.track(key)
	return key
}

func (f *redisIntegrationFixture) track(key string) {
	f.testingT.Helper()
	if key == "" {
		f.testingT.Fatal("attempted to track an empty Redis key")
	}
	f.keys[key] = struct{}{}
}

func (f *redisIntegrationFixture) trackSession(sessionID string) {
	f.testingT.Helper()
	// Session IDs are securely generated by Service, so they cannot be given
	// the fixture prefix. Track their exact keys instead of using a broad Redis
	// deletion command.
	f.track(sessionKey(sessionID))
}

func (f *redisIntegrationFixture) commandCalls(t *testing.T, command string) int64 {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	stats, err := f.store.client.Info(ctx, "commandstats").Result()
	if err != nil {
		t.Fatalf("read Redis command stats: %v", err)
	}
	prefix := "cmdstat_" + strings.ToLower(command) + ":"
	for _, line := range strings.Split(stats, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		for _, field := range strings.Split(strings.TrimPrefix(line, prefix), ",") {
			name, value, found := strings.Cut(field, "=")
			if !found || name != "calls" {
				continue
			}
			calls, err := strconv.ParseInt(value, 10, 64)
			if err != nil {
				t.Fatalf("parse Redis %s call count %q: %v", command, value, err)
			}
			return calls
		}
	}
	t.Fatalf("Redis command stats did not include %q", command)
	return 0
}

func redisIntegrationConfig(redisURL string) config.IdentityConfig {
	return config.IdentityConfig{
		SessionCookieName:          "axi_session",
		SessionTTL:                 8 * time.Hour,
		SessionIdleTTL:             time.Hour,
		SessionAbsoluteTTL:         4 * time.Hour,
		EmailLoginOwnerEmail:       "owner@axi.test",
		EmailLoginSubject:          "owner-subject",
		RedisURL:                   redisURL,
		RequireDurableSessionStore: true,
	}
}

func redisIntegrationRequest(cookieName, sessionID string) *http.Request {
	request := httptest.NewRequest(http.MethodGet, "/api/v1/auth/session", nil)
	request.AddCookie(&http.Cookie{Name: cookieName, Value: sessionID})
	return request
}

func closeRedisIntegrationService(t *testing.T, service *Service) {
	t.Helper()
	if service == nil {
		return
	}
	if err := service.Close(); err != nil {
		t.Errorf("close Redis-backed identity service: %v", err)
	}
}

func TestRedisIntegrationNewPingsAndRestoresEmailSessionAfterGatewayRestart(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	clock := &testClock{now: time.Date(2026, 8, 11, 20, 0, 0, 0, time.UTC)}

	pingCallsBeforeNew := fixture.commandCalls(t, "ping")
	issuer, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed issuer: %v", err)
	}
	issuerClosed := false
	t.Cleanup(func() {
		if !issuerClosed {
			closeRedisIntegrationService(t, issuer)
		}
	})
	if pingCallsAfterNew := fixture.commandCalls(t, "ping"); pingCallsAfterNew <= pingCallsBeforeNew {
		t.Fatalf("New did not issue a Redis PING: before=%d after=%d", pingCallsBeforeNew, pingCallsAfterNew)
	}
	issuer.now = clock.Now

	sessionID, err := issuer.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(sessionID)
	if err := issuer.Close(); err != nil {
		t.Fatalf("close issuer before simulated gateway restart: %v", err)
	}
	issuerClosed = true

	restarted, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("recreate Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, restarted) })
	restarted.now = clock.Now

	principal, restoredID, err := restarted.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, sessionID))
	if err != nil {
		t.Fatalf("restore session after gateway restart: %v", err)
	}
	if principal.Subject != "owner-subject" || principal.Email != "owner@axi.test" || restoredID != sessionID {
		t.Fatalf("restored principal/session = %#v / %q, want owner principal / %q", principal, restoredID, sessionID)
	}
}

func TestRedisIntegrationRotateThenPredecessorLogoutRevokesSuccessor(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	cfg.SessionRenewAfter = 5 * time.Minute
	clock := &testClock{now: time.Date(2026, 8, 11, 20, 30, 0, 0, time.UTC)}

	service, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, service) })
	service.now = clock.Now

	predecessorID, err := service.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(predecessorID)
	clock.Advance(cfg.SessionRenewAfter)
	_, successorID, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID))
	if err != nil {
		t.Fatalf("rotate Redis-backed session: %v", err)
	}
	if successorID == "" || successorID == predecessorID {
		t.Fatalf("rotated session ID = %q, predecessor = %q", successorID, predecessorID)
	}
	fixture.trackSession(successorID)

	if err := service.Logout(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID)); err != nil {
		t.Fatalf("logout with rotated predecessor cookie: %v", err)
	}
	if _, _, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, successorID)); !errors.Is(err, ErrUnauthorized) {
		t.Fatalf("successor remained restorable after predecessor logout: %v", err)
	}
}

func TestRedisIntegrationLogoutThenStaleRotateCannotCreateSuccessor(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	clock := &testClock{now: time.Date(2026, 8, 11, 21, 0, 0, 0, time.UTC)}

	service, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, service) })
	service.now = clock.Now

	predecessorID, err := service.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(predecessorID)
	predecessorKey := sessionKey(predecessorID)
	expected, err := fixture.store.Get(ctx, predecessorKey)
	if err != nil {
		t.Fatalf("read active predecessor before logout: %v", err)
	}

	if err := service.Logout(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID)); err != nil {
		t.Fatalf("logout active predecessor: %v", err)
	}
	successorKey := fixture.key("logout-then-stale-rotate-successor")
	tombstone := []byte(`{"supersededBy":"logout-then-stale-rotate-successor"}`)
	if err := fixture.store.Rotate(ctx, predecessorKey, expected, successorKey, []byte("must-not-exist"), time.Hour, tombstone, time.Hour); !errors.Is(err, ErrRecordNotFound) {
		t.Fatalf("Rotate after logout error = %v, want ErrRecordNotFound", err)
	}
	if _, err := fixture.store.Get(ctx, successorKey); !errors.Is(err, ErrRecordNotFound) {
		t.Fatalf("stale Rotate created successor after logout: %v", err)
	}
}

func TestRedisIntegrationRotateRejectsInvalidTTLsWithoutPartialWrites(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	invalidTTLs := []time.Duration{0, -time.Millisecond, 500 * time.Microsecond}
	for _, invalidTTL := range invalidTTLs {
		t.Run(invalidTTL.String(), func(t *testing.T) {
			oldKey := fixture.key("invalid-ttl-old")
			newKey := fixture.key("invalid-ttl-new")
			oldValue := []byte("old-value")
			originalNewValue := []byte("original-new-value")
			if err := fixture.store.Set(ctx, oldKey, oldValue, time.Hour); err != nil {
				t.Fatalf("set old record: %v", err)
			}
			expected, err := fixture.store.Get(ctx, oldKey)
			if err != nil {
				t.Fatalf("read old record: %v", err)
			}
			if err := fixture.store.Set(ctx, newKey, originalNewValue, time.Hour); err != nil {
				t.Fatalf("set successor baseline: %v", err)
			}
			tombstone := []byte(`{"supersededBy":"invalid-ttl-successor"}`)

			if err := fixture.store.Rotate(ctx, oldKey, expected, newKey, []byte("new-value"), invalidTTL, tombstone, time.Hour); !errors.Is(err, ErrRecordTTLTooShort) {
				t.Fatalf("Rotate invalid successor TTL error = %v, want ErrRecordTTLTooShort", err)
			}
			assertRedisIntegrationValue(t, fixture.store, ctx, oldKey, expected)
			assertRedisIntegrationValue(t, fixture.store, ctx, newKey, originalNewValue)

			if err := fixture.store.Rotate(ctx, oldKey, expected, newKey, []byte("new-value"), time.Hour, tombstone, invalidTTL); !errors.Is(err, ErrRecordTTLTooShort) {
				t.Fatalf("Rotate invalid tombstone TTL error = %v, want ErrRecordTTLTooShort", err)
			}
			assertRedisIntegrationValue(t, fixture.store, ctx, oldKey, expected)
			assertRedisIntegrationValue(t, fixture.store, ctx, newKey, originalNewValue)
		})
	}
}

func assertRedisIntegrationValue(t *testing.T, store *RedisRecordStore, ctx context.Context, key string, want []byte) {
	t.Helper()
	got, err := store.Get(ctx, key)
	if err != nil {
		t.Fatalf("read Redis key %q: %v", key, err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("Redis key %q = %q, want %q", key, got, want)
	}
}
