package identity

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/epap/api-gateway/config"
)

const redisIntegrationURLEnv = "GATEWAY_REDIS_INTEGRATION_URL"

var redisIntegrationFactoryInstallMu sync.Mutex

// redisIntegrationFixture owns only the keys it creates. It deliberately does
// not use SCAN, KEYS, FLUSHDB, or FLUSHALL: an explicitly configured Redis URL
// can point at DB 0 shared with an unrelated local process.
type redisIntegrationFixture struct {
	testingT *testing.T
	url      string
	store    *RedisRecordStore
	prefix   string
	keys     map[string]struct{}
	nextKey  int
}

func newRedisIntegrationFixture(t *testing.T) *redisIntegrationFixture {
	t.Helper()
	url := strings.TrimSpace(os.Getenv(redisIntegrationURLEnv))
	if url == "" {
		t.Skipf("set %s to run against a real Redis server", redisIntegrationURLEnv)
	}

	store, err := NewRedisRecordStore(url)
	if err != nil {
		t.Fatalf("parse %s: %v", redisIntegrationURLEnv, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := store.Ping(ctx); err != nil {
		_ = store.Close()
		t.Fatalf("ping Redis from %s: %v", redisIntegrationURLEnv, err)
	}
	suffix, err := opaqueValue()
	if err != nil {
		_ = store.Close()
		t.Fatalf("create Redis test key prefix: %v", err)
	}
	fixture := &redisIntegrationFixture{
		testingT: t,
		url:      url,
		store:    store,
		prefix:   "axi:test:api-gateway:identity:" + suffix,
		keys:     make(map[string]struct{}),
	}
	t.Cleanup(fixture.cleanup)
	return fixture
}

func (f *redisIntegrationFixture) cleanup() {
	f.testingT.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	for key := range f.keys {
		if err := f.store.Delete(ctx, key); err != nil {
			f.testingT.Errorf("clean up Redis key %q: %v", key, err)
			continue
		}
		if _, err := f.store.Get(ctx, key); !errors.Is(err, ErrRecordNotFound) {
			f.testingT.Errorf("Redis test key %q remained after cleanup: %v", key, err)
		}
	}
	if err := f.store.Close(); err != nil {
		f.testingT.Errorf("close Redis test store: %v", err)
	}
}

func (f *redisIntegrationFixture) key(label string) string {
	f.testingT.Helper()
	f.nextKey++
	key := fmt.Sprintf("%s:%d:%s", f.prefix, f.nextKey, label)
	f.track(key)
	return key
}

func (f *redisIntegrationFixture) track(key string) {
	f.testingT.Helper()
	if key == "" {
		f.testingT.Fatal("attempted to track an empty Redis key")
	}
	f.keys[key] = struct{}{}
}

func (f *redisIntegrationFixture) trackSession(sessionID string) {
	f.testingT.Helper()
	// Session IDs are securely generated by Service, so they cannot be given
	// the fixture prefix. Track their exact keys instead of using a broad Redis
	// deletion command.
	f.track(sessionKey(sessionID))
}

// redisIntegrationPingFactory wraps only stores that this test constructs.
// Its counter deliberately advances only after the underlying real Redis PING
// succeeds, which gives the startup assertion a local, ACL-independent owner.
type redisIntegrationPingFactory struct {
	trackedURL      string
	mu              sync.Mutex
	constructed     int
	successfulPings int
}

type redisIntegrationPingStore struct {
	*RedisRecordStore
	factory *redisIntegrationPingFactory
}

func (f *redisIntegrationPingFactory) newStore(redisURL string) (RecordStore, error) {
	store, err := NewRedisRecordStore(redisURL)
	if err != nil {
		return nil, err
	}
	if redisURL != f.trackedURL {
		return store, nil
	}
	f.mu.Lock()
	f.constructed++
	f.mu.Unlock()
	return &redisIntegrationPingStore{RedisRecordStore: store, factory: f}, nil
}

func (s *redisIntegrationPingStore) Ping(ctx context.Context) error {
	if err := s.RedisRecordStore.Ping(ctx); err != nil {
		return err
	}
	s.factory.mu.Lock()
	s.factory.successfulPings++
	s.factory.mu.Unlock()
	return nil
}

func (f *redisIntegrationPingFactory) stats() (constructed, successfulPings int) {
	f.mu.Lock()
	defer f.mu.Unlock()
	return f.constructed, f.successfulPings
}

func installRedisIntegrationPingFactory(t *testing.T, trackedURL string) *redisIntegrationPingFactory {
	t.Helper()
	redisIntegrationFactoryInstallMu.Lock()
	t.Cleanup(func() {
		redisIntegrationFactoryInstallMu.Unlock()
	})
	factory := &redisIntegrationPingFactory{trackedURL: trackedURL}
	newRedisRecordStoreMu.Lock()
	previous := newRedisRecordStore
	newRedisRecordStore = factory.newStore
	newRedisRecordStoreMu.Unlock()
	t.Cleanup(func() {
		newRedisRecordStoreMu.Lock()
		newRedisRecordStore = previous
		newRedisRecordStoreMu.Unlock()
	})
	return factory
}

func redisIntegrationConfig(redisURL string) config.IdentityConfig {
	return config.IdentityConfig{
		SessionCookieName:          "axi_session",
		SessionTTL:                 8 * time.Hour,
		SessionIdleTTL:             time.Hour,
		SessionAbsoluteTTL:         4 * time.Hour,
		EmailLoginOwnerEmail:       "owner@axi.test",
		EmailLoginSubject:          "owner-subject",
		RedisURL:                   redisURL,
		RequireDurableSessionStore: true,
	}
}

func redisIntegrationRequest(cookieName, sessionID string) *http.Request {
	request := httptest.NewRequest(http.MethodGet, "/api/v1/auth/session", nil)
	request.AddCookie(&http.Cookie{Name: cookieName, Value: sessionID})
	return request
}

func closeRedisIntegrationService(t *testing.T, service *Service) {
	t.Helper()
	if service == nil {
		return
	}
	if err := service.Close(); err != nil {
		t.Errorf("close Redis-backed identity service: %v", err)
	}
}

func TestRedisIntegrationNewPingsAndRestoresEmailSessionAfterGatewayRestart(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	clock := &testClock{now: time.Date(2026, 8, 11, 20, 0, 0, 0, time.UTC)}
	pingFactory := installRedisIntegrationPingFactory(t, fixture.url)

	issuer, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed issuer: %v", err)
	}
	issuerClosed := false
	t.Cleanup(func() {
		if !issuerClosed {
			closeRedisIntegrationService(t, issuer)
		}
	})
	if constructed, successfulPings := pingFactory.stats(); constructed != 1 || successfulPings != 1 {
		t.Fatalf("issuer Redis store/PING counts = %d/%d, want 1/1", constructed, successfulPings)
	}
	issuer.now = clock.Now

	sessionID, err := issuer.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(sessionID)
	if err := issuer.Close(); err != nil {
		t.Fatalf("close issuer before simulated gateway restart: %v", err)
	}
	issuerClosed = true

	restarted, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("recreate Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, restarted) })
	if constructed, successfulPings := pingFactory.stats(); constructed != 2 || successfulPings != 2 {
		t.Fatalf("restarted Redis store/PING counts = %d/%d, want 2/2", constructed, successfulPings)
	}
	restarted.now = clock.Now

	principal, restoredID, err := restarted.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, sessionID))
	if err != nil {
		t.Fatalf("restore session after gateway restart: %v", err)
	}
	if principal.Subject != "owner-subject" || principal.Email != "owner@axi.test" || restoredID != sessionID {
		t.Fatalf("restored principal/session = %#v / %q, want owner principal / %q", principal, restoredID, sessionID)
	}
}

func TestRedisIntegrationRotateThenPredecessorLogoutRevokesSuccessor(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	cfg.SessionRenewAfter = 5 * time.Minute
	clock := &testClock{now: time.Date(2026, 8, 11, 20, 30, 0, 0, time.UTC)}

	service, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, service) })
	service.now = clock.Now

	predecessorID, err := service.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(predecessorID)
	clock.Advance(cfg.SessionRenewAfter)
	_, successorID, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID))
	if err != nil {
		t.Fatalf("rotate Redis-backed session: %v", err)
	}
	if successorID == "" || successorID == predecessorID {
		t.Fatalf("rotated session ID = %q, predecessor = %q", successorID, predecessorID)
	}
	fixture.trackSession(successorID)
	principal, restoredID, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, successorID))
	if err != nil {
		t.Fatalf("restore successor before predecessor logout: %v", err)
	}
	if principal.Subject != "owner-subject" || principal.Email != "owner@axi.test" || restoredID != successorID {
		t.Fatalf("restored successor principal/session = %#v / %q, want owner principal / %q", principal, restoredID, successorID)
	}

	if err := service.Logout(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID)); err != nil {
		t.Fatalf("logout with rotated predecessor cookie: %v", err)
	}
	if _, _, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, successorID)); !errors.Is(err, ErrUnauthorized) {
		t.Fatalf("successor remained restorable after predecessor logout: %v", err)
	}
}

// pauseFirstCompareAndDeleteStore forces the window where Logout has read an
// active predecessor but has not yet issued its conditional delete. Its
// embedded store remains the real RedisRecordStore used by this integration
// test; only the first CompareAndDelete call is delayed.
type pauseFirstCompareAndDeleteStore struct {
	RecordStore
	firstCompareAndDeleteEntered chan struct{}
	allowFirstCompareAndDelete   chan struct{}
	firstCompareAndDelete        sync.Once
}

func (s *pauseFirstCompareAndDeleteStore) CompareAndDelete(ctx context.Context, key string, expected []byte) error {
	pause := false
	s.firstCompareAndDelete.Do(func() {
		pause = true
		close(s.firstCompareAndDeleteEntered)
	})
	if pause {
		select {
		case <-s.allowFirstCompareAndDelete:
		case <-ctx.Done():
			return ctx.Err()
		}
	}
	return s.RecordStore.CompareAndDelete(ctx, key, expected)
}

func TestRedisIntegrationLogoutRereadsTombstoneAfterConcurrentRotate(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	cfg := redisIntegrationConfig(fixture.url)
	cfg.SessionRenewAfter = 5 * time.Minute
	clock := &testClock{now: time.Date(2026, 8, 11, 20, 45, 0, 0, time.UTC)}
	logoutStore, err := NewRedisRecordStore(fixture.url)
	if err != nil {
		t.Fatalf("create Redis store for concurrent logout: %v", err)
	}
	if err := logoutStore.Ping(ctx); err != nil {
		_ = logoutStore.Close()
		t.Fatalf("ping Redis store for concurrent logout: %v", err)
	}
	barrierStore := &pauseFirstCompareAndDeleteStore{
		RecordStore:                  logoutStore,
		firstCompareAndDeleteEntered: make(chan struct{}),
		allowFirstCompareAndDelete:   make(chan struct{}),
	}
	var releaseBarrier sync.Once
	release := func() {
		releaseBarrier.Do(func() {
			close(barrierStore.allowFirstCompareAndDelete)
		})
	}
	defer release()
	service := NewForTest(cfg, barrierStore, nil, clock.Now)
	t.Cleanup(func() { closeRedisIntegrationService(t, service) })

	predecessorID, err := service.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(predecessorID)
	logoutResult := make(chan error, 1)
	go func() {
		logoutResult <- service.Logout(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID))
	}()
	select {
	case <-barrierStore.firstCompareAndDeleteEntered:
	case <-ctx.Done():
		t.Fatalf("Logout did not reach its first CompareAndDelete: %v", ctx.Err())
	}

	clock.Advance(cfg.SessionRenewAfter)
	principal, successorID, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID))
	if err != nil {
		t.Fatalf("rotate predecessor while Logout is paused: %v", err)
	}
	if principal.Subject != "owner-subject" || principal.Email != "owner@axi.test" || successorID == "" || successorID == predecessorID {
		t.Fatalf("concurrent rotation principal/session = %#v / %q, predecessor %q", principal, successorID, predecessorID)
	}
	fixture.trackSession(successorID)

	release()
	select {
	case err := <-logoutResult:
		if err != nil {
			t.Fatalf("Logout after concurrent rotate: %v", err)
		}
	case <-ctx.Done():
		t.Fatalf("Logout did not finish after releasing CompareAndDelete: %v", ctx.Err())
	}
	if _, _, err := service.RestoreSession(ctx, redisIntegrationRequest(cfg.SessionCookieName, successorID)); !errors.Is(err, ErrUnauthorized) {
		t.Fatalf("successor remained restorable after concurrent predecessor logout: %v", err)
	}
}

func TestRedisIntegrationLogoutThenStaleRotateCannotCreateSuccessor(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	cfg := redisIntegrationConfig(fixture.url)
	clock := &testClock{now: time.Date(2026, 8, 11, 21, 0, 0, 0, time.UTC)}

	service, err := New(ctx, cfg)
	if err != nil {
		t.Fatalf("New Redis-backed service: %v", err)
	}
	t.Cleanup(func() { closeRedisIntegrationService(t, service) })
	service.now = clock.Now

	predecessorID, err := service.IssueEmailSession(ctx, "owner@axi.test")
	if err != nil {
		t.Fatalf("issue Redis-backed email session: %v", err)
	}
	fixture.trackSession(predecessorID)
	predecessorKey := sessionKey(predecessorID)
	expected, err := fixture.store.Get(ctx, predecessorKey)
	if err != nil {
		t.Fatalf("read active predecessor before logout: %v", err)
	}

	if err := service.Logout(ctx, redisIntegrationRequest(cfg.SessionCookieName, predecessorID)); err != nil {
		t.Fatalf("logout active predecessor: %v", err)
	}
	if _, err := fixture.store.Get(ctx, predecessorKey); !errors.Is(err, ErrRecordNotFound) {
		t.Fatalf("predecessor remained after logout: %v", err)
	}
	successorKey := fixture.key("logout-then-stale-rotate-successor")
	tombstone := []byte(`{"supersededBy":"logout-then-stale-rotate-successor"}`)
	if err := fixture.store.Rotate(ctx, predecessorKey, expected, successorKey, []byte("must-not-exist"), time.Hour, tombstone, time.Hour); !errors.Is(err, ErrRecordNotFound) {
		t.Fatalf("Rotate after logout error = %v, want ErrRecordNotFound", err)
	}
	if _, err := fixture.store.Get(ctx, successorKey); !errors.Is(err, ErrRecordNotFound) {
		t.Fatalf("stale Rotate created successor after logout: %v", err)
	}
}

func TestRedisIntegrationRotateRejectsInvalidTTLsWithoutPartialWrites(t *testing.T) {
	fixture := newRedisIntegrationFixture(t)
	ctx := context.Background()
	invalidTTLs := []time.Duration{0, -time.Millisecond, 500 * time.Microsecond}
	for _, invalidTTL := range invalidTTLs {
		t.Run(invalidTTL.String(), func(t *testing.T) {
			assertInvalidRotateLeavesRedisRecordsUntouched(t, fixture, ctx, "invalid-successor-ttl", invalidTTL, 2*time.Hour)
			assertInvalidRotateLeavesRedisRecordsUntouched(t, fixture, ctx, "invalid-tombstone-ttl", 2*time.Hour, invalidTTL)
		})
	}
}

const (
	redisIntegrationMinimumTTLDecay      = 30 * time.Millisecond
	redisIntegrationTTLIncreaseTolerance = 5 * time.Millisecond
)

type redisIntegrationRecordSnapshot struct {
	value []byte
	ttl   time.Duration
}

func assertInvalidRotateLeavesRedisRecordsUntouched(t *testing.T, fixture *redisIntegrationFixture, ctx context.Context, label string, newTTL, tombstoneTTL time.Duration) {
	t.Helper()
	oldKey := fixture.key(label + "-old")
	newKey := fixture.key(label + "-new")
	oldValue := []byte("old-value")
	originalNewValue := []byte("original-new-value")
	const baselineTTL = 45 * time.Minute
	if err := fixture.store.Set(ctx, oldKey, oldValue, baselineTTL); err != nil {
		t.Fatalf("set old record for %s: %v", label, err)
	}
	expected, err := fixture.store.Get(ctx, oldKey)
	if err != nil {
		t.Fatalf("read old record for %s: %v", label, err)
	}
	if err := fixture.store.Set(ctx, newKey, originalNewValue, baselineTTL); err != nil {
		t.Fatalf("set successor baseline for %s: %v", label, err)
	}
	oldInitial := redisIntegrationSnapshot(t, fixture.store, ctx, oldKey)
	newInitial := redisIntegrationSnapshot(t, fixture.store, ctx, newKey)
	oldBefore := redisIntegrationSnapshotAfterTTLDecay(t, fixture.store, ctx, oldKey, oldInitial)
	newBefore := redisIntegrationSnapshotAfterTTLDecay(t, fixture.store, ctx, newKey, newInitial)
	tombstone := []byte(`{"supersededBy":"invalid-ttl-successor"}`)
	if err := fixture.store.Rotate(ctx, oldKey, expected, newKey, []byte("new-value"), newTTL, tombstone, tombstoneTTL); !errors.Is(err, ErrRecordTTLTooShort) {
		t.Fatalf("Rotate %s error = %v, want ErrRecordTTLTooShort", label, err)
	}
	assertRedisIntegrationSnapshotUnchanged(t, fixture.store, ctx, oldKey, oldBefore)
	assertRedisIntegrationSnapshotUnchanged(t, fixture.store, ctx, newKey, newBefore)
}

func redisIntegrationSnapshot(t *testing.T, store *RedisRecordStore, ctx context.Context, key string) redisIntegrationRecordSnapshot {
	t.Helper()
	value, err := store.Get(ctx, key)
	if err != nil {
		t.Fatalf("read Redis key %q: %v", key, err)
	}
	ttl, err := store.client.PTTL(ctx, key).Result()
	if err != nil {
		t.Fatalf("read Redis PTTL for %q: %v", key, err)
	}
	if ttl <= 0 {
		t.Fatalf("Redis PTTL for %q = %s, want live positive TTL", key, ttl)
	}
	return redisIntegrationRecordSnapshot{value: value, ttl: ttl}
}

func redisIntegrationSnapshotAfterTTLDecay(t *testing.T, store *RedisRecordStore, ctx context.Context, key string, initial redisIntegrationRecordSnapshot) redisIntegrationRecordSnapshot {
	t.Helper()
	deadline := time.Now().Add(2 * time.Second)
	for {
		current := redisIntegrationSnapshot(t, store, ctx, key)
		if initial.ttl-current.ttl >= redisIntegrationMinimumTTLDecay {
			return current
		}
		if time.Now().After(deadline) {
			t.Fatalf("Redis PTTL for %q did not decay by %s: initial=%s current=%s", key, redisIntegrationMinimumTTLDecay, initial.ttl, current.ttl)
		}
		time.Sleep(5 * time.Millisecond)
	}
}

func assertRedisIntegrationSnapshotUnchanged(t *testing.T, store *RedisRecordStore, ctx context.Context, key string, before redisIntegrationRecordSnapshot) {
	t.Helper()
	after := redisIntegrationSnapshot(t, store, ctx, key)
	if !bytes.Equal(after.value, before.value) {
		t.Fatalf("Redis key %q value = %q, want unchanged %q", key, after.value, before.value)
	}
	if ttlIncrease := after.ttl - before.ttl; ttlIncrease > redisIntegrationTTLIncreaseTolerance {
		t.Fatalf("Redis key %q PTTL increased by %s (%s -> %s), want no increase beyond %s Redis rounding tolerance", key, ttlIncrease, before.ttl, after.ttl, redisIntegrationTTLIncreaseTolerance)
	}
}
