/**
 * Pagination cursor registry — opaque, server-side tokens for the narrow
 * resource-search/v1 contract (POST /resource/search).
 *
 * Background:
 *   The previous implementation derived `nextCursor` from the caller's
 *   requestId (`${requestId}:${projection.length}`). That was not opaque:
 *   - `requestId` is supplied by the client (`x-request-id` echo path),
 *     so a future caller could mint, replay, or forge pagination tokens.
 *   - The token structure leaked the offset directly into the response.
 *   - The Soul BFF (apps/web-admin, apps/web-bff, etc.) and the Android
 *     front-end would have to round-trip server-side bookkeeping through
 *     the client; we never wanted them to be in that loop.
 *
 * Contract (GHA-NEXT-046 / H-2 fix):
 *   - Tokens are random base64url strings, generated by `crypto.randomBytes`.
 *   - Tokens are mapped to a single piece of server state: the upstream
 *     `requestId` plus the next page number and the page-size the client
 *     used. Clients cannot influence the encoded state.
 *   - Tokens carry a TTL. `evictExpired()` runs lazily on every lookup
 *     and on a 60-second timer to keep memory bounded.
 *   - `decode(token)` is the ONLY way to recover state. Invalid, expired,
 *     or unknown tokens map to a tagged result so callers can fail closed
 *     at the HTTP boundary without leaking the registry's internal layout.
 *   - All internal field names are kept inside this module. The registry
 *     is the source of truth for the opaque-pagination invariant; the
 *     server route must never read or write `token → requestId` mapping
 *     outside `encode` / `decode`.
 *
 * Style:
 *   - Pure Node standard library, no platform deps.
 *   - Functional shape: stateless callers own a single `CursorRegistry`
 *     instance and thread it through `ServerState`.
 */

import { randomBytes } from "node:crypto";

/** Default TTL — five minutes is the working set for a single
 *  paginated session. Long enough for slow clients, short enough to
 *  bound memory growth. */
export const DEFAULT_CURSOR_TTL_MS = 5 * 60 * 1000;

/** How often `evictExpired()` runs on its own clock. The lazy eviction
 *  on every lookup keeps the steady-state size tight; the timer guards
 *  the case where a stream of unrelated requests never trigger the
 *  hot path. */
const EVICTION_INTERVAL_MS = 60 * 1000;

/**
 * Server-side cursor state. `page` is the next page number to return
 * (1-based; first page is `1`). `pageSize` is captured so subsequent
 * pages keep the same size even if the client would have asked for a
 * different size later — pagination is stable per token.
 */
export interface CursorState {
  requestId: string;
  page: number;
  pageSize: number;
}

interface CursorEntry extends CursorState {
  expiresAt: number;
}

export type CursorDecodeResult =
  | { ok: true; state: CursorState }
  | { ok: false; reason: "missing" | "expired" | "malformed" | "unknown" };

export interface CursorRegistryOptions {
  ttlMs?: number;
  /** Optional seed for deterministic tests. When supplied, random
   *  generation falls back to a counter-style sequence so tests can
   *  assert "the cursor is not the same as the input" without
   *  depending on the RNG. */
  rng?: () => string;
  /** Override `Date.now` for tests. */
  now?: () => number;
}

export class CursorRegistry {
  private readonly ttlMs: number;
  private readonly rng: () => string;
  private readonly now: () => number;
  private readonly entries = new Map<string, CursorEntry>();
  private evictionTimer: NodeJS.Timeout | null = null;

  constructor(options: CursorRegistryOptions = {}) {
    this.ttlMs = options.ttlMs ?? DEFAULT_CURSOR_TTL_MS;
    this.rng = options.rng ?? defaultRng;
    this.now = options.now ?? Date.now;
    if (options.ttlMs !== 0) {
      // Only spin up the timer when the registry is allowed to hold
      // entries long enough for it to matter.
      this.evictionTimer = setInterval(() => this.evictExpired(), EVICTION_INTERVAL_MS);
      // The timer must not keep the process alive on shutdown.
      if (typeof this.evictionTimer.unref === "function") this.evictionTimer.unref();
    }
  }

  /**
   * Encode a server-side state into an opaque token. The token has no
   * externally meaningful structure; clients must treat it as a
   * black box and pass it back verbatim on the next request.
   */
  encode(state: CursorState): string {
    if (state.page < 1) throw new Error("cursor page must be >= 1");
    if (state.pageSize < 1) throw new Error("cursor pageSize must be >= 1");
    if (!state.requestId || state.requestId.length > 200) {
      throw new Error("cursor requestId must be 1..200 chars");
    }
    const token = this.rng();
    this.entries.set(token, {
      ...state,
      expiresAt: this.now() + this.ttlMs,
    });
    return token;
  }

  /**
   * Look up a token. Returns a tagged result so the caller can map
   * each failure mode onto the right HTTP error without inspecting
   * the registry. The order of checks matters: expired takes priority
   * over unknown so a re-used expired token is reported as `expired`,
   * not `unknown`.
   */
  decode(token: string | undefined): CursorDecodeResult {
    if (!token || typeof token !== "string") {
      return { ok: false, reason: "missing" };
    }
    if (token.length < 8 || token.length > 200) {
      return { ok: false, reason: "malformed" };
    }
    // Lazy eviction of OTHER expired entries — but we must NOT drop
    // the entry we are about to look up, otherwise the `expired`
    // reason can never fire (it degenerates into `unknown`). The
    // `expired` branch below is responsible for deleting the looked-up
    // token once it has been reported.
    this.evictExpiredExcept(token);
    const entry = this.entries.get(token);
    if (!entry) return { ok: false, reason: "unknown" };
    if (entry.expiresAt <= this.now()) {
      this.entries.delete(token);
      return { ok: false, reason: "expired" };
    }
    return {
      ok: true,
      state: {
        requestId: entry.requestId,
        page: entry.page,
        pageSize: entry.pageSize,
      },
    };
  }

  /**
   * Drop a single token. Used after a request fails mid-page so a
   * retry with the same cursor does not silently resume a partial
   * session.
   */
  invalidate(token: string): void {
    this.entries.delete(token);
  }

  /** Visible for tests. */
  size(): number {
    return this.entries.size;
  }

  /** Visible for tests — drop everything. */
  clear(): void {
    this.entries.clear();
  }

  /**
   * Stop the eviction timer. Tests call this in `afterEach`; the
   * production server relies on process exit to collect the handle.
   */
  dispose(): void {
    if (this.evictionTimer) {
      clearInterval(this.evictionTimer);
      this.evictionTimer = null;
    }
    this.entries.clear();
  }

  private evictExpired(): void {
    const now = this.now();
    for (const [token, entry] of this.entries) {
      if (entry.expiresAt <= now) this.entries.delete(token);
    }
  }

  /** Same as `evictExpired` but leaves `keepToken` (if present) alone so
   *  the caller can still observe the `expired` branch. */
  private evictExpiredExcept(keepToken: string): void {
    const now = this.now();
    for (const [token, entry] of this.entries) {
      if (token === keepToken) continue;
      if (entry.expiresAt <= now) this.entries.delete(token);
    }
  }
}

/** URL-safe base64 alphabet used by both the production RNG
 *  (`crypto.randomBytes → base64url`) and the deterministic test
 *  counter RNG. */
const DEFAULT_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

const defaultRng = (): string => {
  // 18 bytes → 24 base64url chars. Long enough to be unique across
  // 2^144 search-space, short enough to fit in the 200-char schema cap.
  return randomBytes(18).toString("base64url");
};

// Exposed for the deterministic-RNG test fixture. Generates 24 chars
// from the URL-safe alphabet without using `crypto.randomBytes`.
export const buildCounterRng = (prefix = "cursor"): (() => string) => {
  let counter = 0;
  return () => {
    counter += 1;
    const suffix = counter.toString(36).padStart(6, "0");
    const tail = prefix.padEnd(18, "_").slice(0, 18);
    const raw = (tail + suffix + suffix).slice(0, 24);
    let out = "";
    for (const ch of raw) {
      out += DEFAULT_ALPHABET.includes(ch) ? ch : "_";
    }
    return out;
  };
};
