{{- if and .Values.fileService.persistence.enabled (eq .Values.fileService.storageBackend "local") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "axi-workbench-platform.fullname" . }}-files
  labels:
    {{- include "axi-workbench-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: file-service
spec:
  accessModes:
    {{- toYaml .Values.fileService.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.fileService.persistence.size }}
  {{- with .Values.fileService.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
