{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axi-workbench-platform.serviceAccountName" . }}
  labels:
    {{- include "axi-workbench-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
