import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
// axi-coder lives 7 levels below the workspace root in this layout:
//   <workspace-root>/workspace.graph.json
//   <workspace-root>/workbench/axi-workbench/apps/axi-coder/src/features/product/...
// The depth is annotated here so future maintainers can see exactly how many
// `..` segments to expect. Override via WORKSPACE_GRAPH_JSON for environments
// where the graph is mounted elsewhere (CI matrix, containerised runs).
const DEPTH_FROM_WORKSPACE_ROOT = "../../../../../../../workspace.graph.json";

function resolveGraphPath(): string {
  if (process.env.WORKSPACE_GRAPH_JSON) {
    return process.env.WORKSPACE_GRAPH_JSON;
  }
  return path.resolve(path.dirname(__filename), DEPTH_FROM_WORKSPACE_ROOT);
}

// Read synchronously at module load so test bodies can rely on the parsed
// shape without awaiting. The graph is regenerated by the post-commit hook
// (`workspace-project graph refresh`) and is therefore expected to be present.
const workspaceGraphPath = resolveGraphPath();
const workspaceGraphRaw = fs.readFileSync(workspaceGraphPath, "utf-8");
export const workspaceGraph = JSON.parse(workspaceGraphRaw) as unknown;